import FAQSection from "./Solutionspart3";
import { FAQ } from '../faq';

const faqs: FAQ[] = [
    {
        question: "What is waste management?",
        answer: "Waste management involves the collection, transportation, processing, recycling, and disposal of waste materials generated by human activities. The goal is to minimize the negative impact of waste on the environment and public health while maximizing resource recovery and sustainability."
    },
    {
        question: "Why is proper waste management important?",
        answer: "Proper waste management is crucial to prevent environmental pollution, conserve natural resources, reduce greenhouse gas emissions, and protect public health. It also promotes circular economy principles by maximizing the value of waste through recycling and reuse."
    },
   
];

const Home: React.FC = () => {
    return (
        <div>
            <FAQSection faqs={faqs} />
        </div>
    );
}

export default Home;
